export const INSTITUTION_DEPARTMENTS = [
  'Financeiro',
  'Contabilidade',
  'Recursos Humanos (RH)',
  'Tecnologia da Informação (TI)',
  'Educação Social de Rua',
  'Educação Profissionalizante',
  'Acolhimento Institucional',
  'Apoio Psicossocial às Famílias',
  'Direitos Humanos',
  'Sensibilização e Mobilização Social',
  'Administrativo',
  'Coordenação',
] as const;

export const INSTITUTION_UNITS = [
  'Senador Alencar - Fortaleza/CE',
  'Agapito dos Santos - Fortaleza/CE',
  'Vicente Pinzón - Fortaleza/CE',
  'Maranguape - CE',
  'Sítio Maranguape - CE',
  'São Gonçalo - CE',
  'Paracuru - CE',
  'Areia Branca - RN',
  'Guamaré - RN',
  'Recife - PE',
  'Itamaracá - PE',
  'São Luiz - MA',
  'Belém - PA',
  'Manaus 1 - AM',
  'Manaus 2 - AM',
  'Caruari - AM',
  'Coari - AM',
  'Oiapoque - AP',
] as const;
